"""initial schema

Revision ID: 49561d028df5
Revises: 
Create Date: 2026-02-22 11:11:39.181029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49561d028df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('world_key', sa.String(length=30), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=500), nullable=False),
    sa.Column('option_b', sa.String(length=500), nullable=False),
    sa.Column('option_c', sa.String(length=500), nullable=False),
    sa.Column('option_d', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam', 'world_key', 'index', name='uq_question_exam_world_index')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_exam_world', ['exam', 'world_key'], unique=False)

    op.create_table('stripe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('level_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_identifier', sa.String(length=20), nullable=False),
    sa.Column('world_key', sa.String(length=30), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('best_score_pct', sa.Float(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('first_passed_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam_identifier', 'world_key', 'level_number', name='uq_level_completion')
    )
    op.create_table('org_exam_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('exam_identifier', sa.String(length=20), nullable=False),
    sa.Column('entitlement_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'exam_identifier', name='uq_org_exam_entitlement'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_identifier', sa.String(length=20), nullable=False),
    sa.Column('world_key', sa.String(length=30), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('chosen_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_qa_user_exam_world_level', ['user_id', 'exam_identifier', 'world_key', 'level_number'], unique=False)

    op.create_table('user_exam_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_identifier', sa.String(length=20), nullable=False),
    sa.Column('entitlement_source', sa.String(length=20), nullable=False),
    sa.Column('entitlement_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(), nullable=True),
    sa.Column('paid_started_at', sa.DateTime(), nullable=True),
    sa.Column('paid_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exam_identifier', name='uq_user_exam_entitlement')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exam_entitlements')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_qa_user_exam_world_level')

    op.drop_table('question_attempts')
    op.drop_table('org_exam_entitlements')
    op.drop_table('level_completions')
    op.drop_table('users')
    op.drop_table('stripe_events')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_exam_world')

    op.drop_table('questions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
